name: Auto Blog Post

on:
  schedule:
    - cron: '0 14 * * *'  # Daily at 2 PM UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Create auto post
      run: |
        pip install -r requirements.txt || true
        python generate_post.py "Passive Income Tips - ${{ github.run_number }}"

    - name: Commit and push
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"
        git add .
        git commit -m "Auto blog post: ${{ github.run_number }}" || echo "No changes to commit"
        git push
